### ISSUE TITLE
Add a user agent to requests made to Treeherder

### ISSUE THREAD

**Issue by edmorley** [klahnakoski/TestLog-ETL#1]
In bug 1230222 we're encouraging consumers of Treeherder's API to set user agent:
https://bugzilla.mozilla.org/show_bug.cgi?id=1230222

It would be great if the requests made in https://github.com/klahnakoski/TestLog-ETL/blob/dev/testlog_etl/imports/treeherder.py added a user agent similar to:
`User-Agent: testlog-etl`

In other projects I've opened a PR myself, however it's not 100% clear to me how to implement this using the `pyLibrary.debug.constants.set()` feature mention here:
https://github.com/klahnakoski/pyLibrary/blob/ad67d6d39e3bc514d854fd409e12d3c74551f5ca/pyLibrary/env/http.py#L70-L73

...since I presume you'd prefer to use that than manually passing headers in the `http.get()` call?

Thanks :-)

**Comment by klahnakoski** [comment]
The Treeherder code has not been used for a while, and is probably broken now.  But, I like the idea if setting the user agent.  I updated the settings files.

The `constants.set()` is done at startup; when modules and classes are injected with configuration from those settings files. 

https://github.com/klahnakoski/TestLog-ETL/commit/4a7efcc5e6a1bfd3d67a2ab0cf015888c5c0d8fd

**Comment by edmorley** [comment]
Thank you :-)
