### ISSUE TITLE
Add  line-level detail, but only the covered lines

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#10]
As per our conversation, the line-level records should be added, since we will need them to find unique covers.  Only add the covered lines.

Be sure to mark the canonical method-level record with a `is_method` flag so we can continue to query at the method level.  Some methods will have no covered lines, so a _null_ record (line number is missing) must be made in its place.   Or maybe, every method gets a _null_ record (and looks exactly like what you have now) , and add copies for each covered line, if any.

This is low priority.

**Comment by klahnakoski** [comment]
Thinking about this more, we can query "nested" documents, which the `covered` and `uncovered` arrays can be made into:  We must name the values in the array:

```
{"covered": [1,2,3,4,5]}
```

would be changed to 

```
{"covered": [{"line":1}, {"line": 2}, {"line": 3}, {"line": 4}, {"line": 5}]}
```

The coverage schema would be changed, I will look that up...

**Comment by klahnakoski** [comment]
When we know the property path name of the `covered` lines we can add it to the schema:

```
"covered": {
    "type": "nested",
    "dynamic": false,
    "properties": {
        "line": {
            "type": "integer",
            "index": "not_analyzed",
            "doc_values": true
        }
    }
},
```

When the transform is ready, I can add this.  (ES may do this automatically).

**Comment by chinhodado** [comment]
So let's see if I understand this correctly: there are two approaches here:
1. Keep the current method-level records, and add in all the line-level records just like before (only for the lines covered)
2. Change the `covered` and `uncovered` arrays in the current method-level record to the following format:
   
   ```
   {"covered": [{"line":1}, {"line": 2}, {"line": 3}, {"line": 4}, {"line": 5}]}
   ```

For approach 1, will size be an issue again like before?

Also, in each approach, how will the query be done to find the unique-lines-covered-by-test for a source file?

**Comment by klahnakoski** [comment]
For option 1:  I hope that making records for just the covered lines will not be too big.

For option 2: We can query the `coverage` array as if it is table.. Something like:

```
{
    "from": "coverage.source.method.covered"
}
```

Consider the database schema required to hold the documents I am proposing:   You would make a `covered_lines` table, with a column (called `line`) and a foreign key back to the method-level record.  A query involving the line table would most likely involve joining the method-level records: Returning one record per line, and the method-level record properties replicated for each . In ActiveData the line table is a "nested table", and has the name of that table set to the property path name of line array.  Querying the line table from ActiveData will include the parent document properties for convenience.

This theory works for nested objects, but may not work for nested values (just a plain array of integers) due to ActiveData limitations of dealing with nested values as their own object.  Maybe leaving the `covered` as an array of integers is best, and I can ensure we can query those line values directly with ActiveData.

**Comment by chinhodado** [comment]
About option 1, the reason that I moved to method-level records in the first place is because of size concern. Wouldn't adding the (covered) line records kind of defeating the purpose of that? In that case, would it be better to just stick with line-level records for everything (both covered and uncovered), and forget about the method-level records?

On a side note, for the use case of finding unique lines covered by test, can we just store the whole file-level covered and uncovered arrays, and leave it to the client to do the finding-unique task after the client has requested all the covered and uncovered arrays of all the tests that touch the source file?

**Comment by klahnakoski** [comment]
yes, maybe.  My only concern is the volume of data required to do that on the client.   We will not go with line-level records.  I will close this.
