### ISSUE TITLE
Code coverage schema is wrong

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#11]
BTW, the code coverage schema [1] appears to be a copy is a mess.  Did I do that?

[1] https://github.com/klahnakoski/TestLog-ETL/blob/codecoverage_new_format/resources/schema/code_coverage.json

**Comment by klahnakoski** [comment]
This is not a big issue, ES is flexible enough to work around this oddity.

**Comment by chinhodado** [comment]
Oh I never noticed that. That file doesn't have any history apart from when you first added it (https://github.com/klahnakoski/TestLog-ETL/commit/feb3e88326f6c2b6852e34eacde03ada4627f44d)

**Comment by klahnakoski** [comment]
Ok, I will fix it when you have the next version of the transformation ready.
