### ISSUE TITLE
Change test.name and test.url in gcov_to_es.py

### ISSUE THREAD

**Issue by marco-c** [klahnakoski/TestLog-ETL#15]
We don't have info about which C++ tests generated which execution counts. We should only use the suite name.

https://github.com/klahnakoski/ActiveData-ETL/blob/eb9be06de2a1accd8300fd06192404f614838178/activedata_etl/transforms/gcov_to_es.py#L258
https://github.com/klahnakoski/ActiveData-ETL/blob/eb9be06de2a1accd8300fd06192404f614838178/activedata_etl/transforms/gcov_to_es.py#L290

**Comment by klahnakoski** [comment]
Yes, either add {"test":{"suite": suitename}}; you should find it in the "task_cluster_record", either under "run.suite.name", or "treeherder"

**Comment by marco-c** [comment]
f936b5aaab45619212d78422f5875a0656d3675e
