### ISSUE TITLE
Don't store lines covered per function

### ISSUE THREAD

**Issue by marco-c** [klahnakoski/TestLog-ETL#17]
The information about lines covered per function might be redundant when we already have lines covered per file.
For high level statistics, I can only see people querying for how many lines and how many functions are covered in a file.
For delving deep, I can only see people querying for which lines and which functions were covered in a file.

Most other tools and services (e.g. `genhtml` or `coveralls`) don't store this information.

**Comment by klahnakoski** [comment]
Lines covered by method give us the ability to know which test (or suite) is best covers a particular method. 

There are details like which suite covers what lines in a function, and if that set of lines is identical, or exclusive.

The high level strategy is to have a single fact table of line-level granularity which simplifies queries. The data is denormalized to make those queries fast, and scale the data to multiple machines.

**Comment by marco-c** [comment]
It seems a little overkill to me. I can see people wanting to know which tests cover a particular function, not which lines of that function.
Is this something that developers were interested in?

**Comment by marco-c** [comment]
Note that, because of how we are storing the data, the size of the JSON file for our format is really large.
For a subset of tests, it is ~2 GB (~300 MB gzip-compressed) with this format, ~30 MB (~2 MB gzip-compressed) with the Coveralls format, ~90 MB (~15 MB gzip-compressed) with the LCOV format.
If we multiply this by the number of test suites we have, we are going to generate several GBs of data every day.
We will need to store the data on S3 in batches, otherwise Python will run out of memory. Is there some utility function in ActiveData-ETL to do that?

**Comment by klahnakoski** [comment]
Yes, you are right, it is a little overkill, and looking at how we used the data, the `file.covered.line` is only used in one place.

Code coverage is a little different in Javascript: It can have coverage outside any method. Therefore, there is coverage document for every method PLUS coverage document for `source.method==null` case.  In this document we must have the `file.covered.line` because we use it in post processing.  In the case of C/C++ I guess there will be coverage for each method, PLUS an extra document to cover the `source.method==null` (which has no lines covered), and contains the `file.covered` data.

I hope that makes sense.

**Comment by klahnakoski** [comment]
Reopening issue so it is easier to find! :)

**Comment by klahnakoski** [comment]
The size of the data is a result of the Taskcuster metadata, yes?

The code should be modified to stream, or process small chucks) to a compressed local file, and send that to S3.  The pyLibrary.aws.s3.Bucket.write_lines() function does that.

**Comment by klahnakoski** [comment]
There is another class called `S3Bucket`, which is currently used to "multiplex" a list of records into multiple files in a single bucket.  It is best explained with this code:

```python
    def extend(self, documents, overwrite=False):
        parts = {}
        for d in wrap(documents):
            parent_key = etl2key(key2etl(d.id).source)
            d.value._id = d.id
            sub = parts.setdefault(parent_key, [])
            sub.append(d.value)

        for k, docs in parts.items():
            self._extend(k, docs, overwrite=overwrite)

        return set(parts.keys())

```

Every document has a dot-separated list of integers called the audit key. These documents are grouped by their `parent_key` (which is everything except that right-most number), and the members of the group are put in a single file:

```python
        for k, docs in parts.items():
            self._extend(k, docs, overwrite=overwrite)
```
In the case of code coverage I beleive we will only be processing one key at a time, so this multiplexing is not needed, and this whole class can be ignore for the purposes of adding files to the bucket.  The only important feature is the correct choice of S3 file name.

You can see in the `_extend()` method the use of `write_lines()`, which will do a good job of not wasting memory.

```python
        if overwrite:
            self.bucket.write_lines(key, (convert.value2json(d) for d in documents))
            return
```

Please continue to use the `pyLibrary.aws.s3.Bucket class` (which is what `S3Bucket` uses).  It will verify your filenames (your keys) are in the correct format.
