### ISSUE TITLE
Are `unified` builds obfuscating `source.file.name`s

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#20]
"unified" builds are intended to go faster by concatenating source files before compilation.  Does this impact the gcno files for coverage builds? Does the concatenation result in obfuscated, or misleading, filenames? If so, unified builds may also be a source of needless redundancy, as each method in a file has copy of the file metadata.

**Comment by marco-c** [comment]
I've verified that this is not a problem. Here's an example with a unified file that contains multiple cpp sources:
[testUnified.txt](https://github.com/klahnakoski/ActiveData-ETL/files/832693/testUnified.txt)
