### ISSUE TITLE
Store functions that are not executed?

### ISSUE THREAD

**Issue by marco-c** [klahnakoski/TestLog-ETL#25]
Should we store functions that are not executed? The pre-existing code was not, so I left the same behavior for now, but I think we should store them.

**Comment by klahnakoski** [comment]
Knowing the functions covered is not I high priority, but it was mentioned in the customer interview, and it is part of [our MVP template ](https://people-mozilla.org/~sledru/reports/coverage-2015/)  The uncovered functions could prove more useful than we imagined.

Do not include the `covered` and `uncovered` line arrays:  The orphan file will have those uncovered lines.

**Comment by marco-c** [comment]
This will be fixed when we update to the latest version of grcov (0.1.5, will be released soon).
