### ISSUE TITLE
json2value check might slow down things

### ISSUE THREAD

**Issue by marco-c** [klahnakoski/TestLog-ETL#27]
https://github.com/klahnakoski/ActiveData-ETL/blob/dev/activedata_etl/transforms/gcov_to_es.py#L153

Can we only do this in debug mode? I implemented the PLACEHOLDER (hacky) solution because Python was quite slow to parse the JSON and then serialize the result.

**Comment by klahnakoski** [comment]
I like that idea.  I will do that.

**Comment by marco-c** [comment]
I think you fixed this ;)
