### ISSUE TITLE
Run grcov directly with the ZIP files, instead of extracting them first

### ISSUE THREAD

**Issue by marco-c** [klahnakoski/TestLog-ETL#29]
If you use the `-z` parameter to launch grcov, it will use the ZIP files directly and we will not need to extract them first.
This makes the process faster, as grcov can start parsing the gcda/gcno files while it is extracting them from the ZIP file.

**Comment by marco-c** [comment]
The `-z` option is no longer needed, you can just pass the paths to the zip files.

**Comment by klahnakoski** [comment]
done
