### ISSUE TITLE
Add revision metadata to CodeCoverage

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#3]
Determine the branch and revision of the code being analyzed, and add the Mercurial markup for it.  Here is an example:

https://github.com/klahnakoski/TestLog-ETL/blob/85812ed54bcc336ab6132d61be065ee0611f0b34/testlog_etl/transforms/pulse_block_to_es.py#L194

**Comment by chinhodado** [comment]
Done by https://github.com/klahnakoski/TestLog-ETL/commit/b79df0abdb68f9634c10c526aaa1ee8eb20dce86

**Comment by klahnakoski** [comment]
Excellent!
