### ISSUE TITLE
Per test coverage off-by-one?

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#39]
Looking at recently imported per-test coverage, it seems some non-code lines are covered:

https://firefox-code-coverage.herokuapp.com/#/file?revision=d4d7e793ebe8&path=/dom/base/nsGlobalWindowInner.cpp

If you select a non code line, with a low number, like line 408

![image](https://user-images.githubusercontent.com/2334429/39892577-17761956-546f-11e8-8112-4a5e90ef41e9.png)

you wil lget a list of suites that covered that line.  Notice it is the per-test coverage suite

![image](https://user-images.githubusercontent.com/2334429/39892616-36507f60-546f-11e8-9b15-32fb6707a3cb.png)

btw, sorry for the duplicate, I inserted the records twice.

**Comment by klahnakoski** [comment]
@marco can you confirm where this off-by-one error is coming from (assuming that is an off-by-one error)

This could be caused by reporting coverage on the wrong revision, assuming a line was added/removed.

**Comment by marco-c** [comment]
It might just be an error in the transform code. The transform code is considering that 0 is the first line, maybe in the other cases we are considering 1 to be the first line?

**Comment by klahnakoski** [comment]
Oh! yes, I do remember that!  Thanks.  I will change it now.

**Comment by klahnakoski** [comment]
done https://github.com/klahnakoski/ActiveData-ETL/commit/7d7a7b9a52a43cff91dfbe4905602eba0f696a17
