### ISSUE TITLE
Add build metatdata to CodeCoverage

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#4]
Using what you can glean from the TaskCluster message, add a "run" property describing the machine that performed the code coverage [1].   Also, add a "build" property describing the particular version of the product being covered [2]. 

[1] https://github.com/klahnakoski/ActiveData/blob/dev/docs/Jobs%20Schema.md#run-columns
[2] https://github.com/klahnakoski/ActiveData/blob/dev/docs/Jobs%20Schema.md#build-columns

**Comment by chinhodado** [comment]
In the TaskCluster task definition, the `suite` is an object with two properties:

```
"suite": {
      "flavor": "browser-chrome-coverage",
      "name": "mochitest"
    },
```

Which one should be used for the `run.suite`? I would guess `name`, but should we retain the `flavor` as well?

For `run.chunk`, TaskCluster provides both the current chunk and the total number of chunks:

```
"chunks": {
      "current": 5,
      "total": 7
    },
```

Should the `total` be discarded?

What are the build options for `run.type`?

In particular, the existing `run` and `bulld` schema seems to be designed for buildbot (?). I'm not sure how well it works with TaskCluster.

An example of a TaskCluster task definition can be seen [here](https://queue.taskcluster.net/v1/task/K8RHWPmQQZaHeO0t4zIMHg). Do you have any suggestion on how to map the info in there to the `run` and `build` properties?

**Comment by chinhodado** [comment]
Some initial work done with 8d7ba3a236444176d70f93ce88b6eabb34ec0223 and df1a669d2116f732c49e6b3a2a33301d6de0c3a0

**Comment by klahnakoski** [comment]
Yes, it would appear the suite.name is good for the run.suite, but we 
should not loose the flavour.  Maybe the suite should be an object just 
like TaskCluster does.  I do not think we need to keep the 
chunks.total:  This will probably be obvious with MAX(run.chunk) .

In general, do your best, and do not throw out information: Redundant 
information (like that chunks.total) can be discarded though.   Once the 
data is in the ES cluster, you can perform some queries to see what the 
domains look like and verify your transform is a good one.

You can query the domain of `run.type`: 
http://activedata.allizom.org/tools/query.html#query_id=KHyUo_1w and it 
looks like "e10s" is the only one.

TaskCluster does seem to say a lot less about what's really happening; 
the task being run knows this, so we must read the tea leaves to fill in 
the appropriate properties.

I will be working on the `run` and `build` properties also, so be sure 
you push what you do get done so I can add to it.

**Comment by chinhodado** [comment]
For `build.date`, is it the timestamp when the build task is created, or when the build is finished?

If I keep the suite flavor, that would change the [documented schema](https://github.com/klahnakoski/ActiveData/blob/dev/docs/Jobs%20Schema.md#run-columns). I guess that's ok?

In the end, there are a lot of info available in the task definition file that is not in the documented schema, so I'm not sure which one I should keep/add and which one I should discard.

**Comment by klahnakoski** [comment]
The `build.date` is actually the date the particular code revision was 
pushed to a branch; the assumption was once a change was pushed, it 
would trigger a build; which is no longer the case.

Yes, you can change the schema!   If you have an actual 
time-of-compilation, then make up an attribute for that: 
`build.compile_timestamp`.  TaskCluster is a new source of data hat can 
teach us more about the domain; so, we can expect the schema change.  
Add any information you feel will help the person looking at 
codecoverage; and discard the information that deals with TaskCluster 
specific machinations.

**Comment by chinhodado** [comment]
I have added some more properties to the build object

**Comment by klahnakoski** [comment]
Good.  We can iterate on this as we find more properties
