### ISSUE TITLE
Use set operators

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#6]
Ignoring the logic of the statements, and if that logic is correct, please the Python set operators instead of the named functions that do that same:

This line

```
method_covered = all_method_lines_set.intersection(obj.covered)   
```

should read 

```
method_covered = all_method_lines_set & obj.covered
```

similarly for 

```
method_uncovered = all_method_lines_set.difference(method_covered)
```

should read 

```
method_uncovered = all_method_lines_set - method_covered
```

**Comment by chinhodado** [comment]
Done: bda787fc092d3384ad7483e1bc388c0a23cd3c71
