### ISSUE TITLE
Add label to the `task` table

### ISSUE THREAD

**Issue by ahal** [klahnakoski/TestLog-ETL#64]
I don't seem to see the task label anywhere in the fields of the `task` table. This is a bit strange as labels are the canonical way of referring to a task.

It does make an appearance in `task.tags`, but it is difficult to query for things in tags, and having a top-level attribute would be much more convenient.

**Comment by klahnakoski** [comment]
@ahal  I assume this belongs to `task.label`

**Comment by klahnakoski** [comment]
@ahal this will be added, in the meantime: Taskcluster's `task.tag.label` is aliased as  `run.key` in ActiveData

**Comment by ahal** [comment]
Ah, maybe that would have been good enough.. but `task.label` will definitely be less confusing for people :). Thanks!

**Comment by klahnakoski** [comment]
@ahal yes.  `task.label` is better:  the `run.key` was from buildbot.

**Comment by klahnakoski** [comment]
data is now arriving:  https://activedata.allizom.org/tools/query.html#query_id=GkWDaWtn
