### ISSUE TITLE
Detect when covered data breaks the assumptions

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#7]
This line

```
new_line.source.percentage_covered = len(obj.covered) / (len(obj.covered) + len(obj.uncovered))
```

uses the data in `obj` to calculate percentage covered, but the code above it uses `method_(un)covered` variables that have been checked against the `all_method_lines_set`.   This makes me nervous:  Please add a check that `method_lines`, `obj.covered` and `obj.uncovered` do not disagree in any way (`obj.covered` and `obj.uncovered` are disjoint, and their union is `method_lines` exactly).

**Comment by klahnakoski** [comment]
Reading more, I see I understood this wrong.  Although there is still the lines with no method that should be considered

**Comment by chinhodado** [comment]
Right. I was think of making a special "method" for those lines that have no method attached to them, but I wasn't sure how to name that special "method". Would an empty name (`""`) work?

**Comment by klahnakoski** [comment]
leave the method name missing entirely

then we can search with `{"missing": "source.method.name"}`

**Comment by klahnakoski** [comment]
This is as good as done.
