### ISSUE TITLE
Some tasks have missing classifications

### ISSUE THREAD

**Issue by marco-c** [klahnakoski/TestLog-ETL#74]
E.g. https://activedata.allizom.org/tools/query.html#query_id=pwlYwH_A:
```
{
	"from":"treeherder",
	"select":"failure",
	"where":{"eq":{"run.taskcluster.id":"QrRarVIoTfSXBSu7BMVBsg"}}
}
```

Returns `not classified`. Instead, the failure was actually classified as intermittent: https://treeherder.mozilla.org/#/jobs?repo=autoland&searchStr=test-linux1804-64-asan%2Fopt-web-platform-tests-e10s-15&revision=b2a188c4998cb7c005d37372a3682ce284d2f5b4.

**Comment by klahnakoski** [comment]
This is probably caused by classification happening in treeherder while the job last_modified is not changed to reflect that change.

**Comment by klahnakoski** [comment]
... I am looking into this.  I will gather the data on the records we need to decide how to fix.

**Comment by klahnakoski** [comment]
This is happening during ingestion into ES:  The version number is not set, or not set properly.

**Comment by klahnakoski** [comment]
The fix has been deployed, but only affects future data.  Past data will be replaced incrementally over the next few days

**Comment by marco-c** [comment]
> The fix has been deployed, but only affects future data. Past data will be replaced incrementally over the next few days

Can you tell me when the backfill will be finished?

**Comment by klahnakoski** [comment]
@marco looks like Monday: The plan is:

* The treeherder table is in 3-month indexes.  I am copying the last four, but it is taking hours: It appears the `_reindex` goes through a single node  
* I assign the `treeherder`alias to the copies
* delete original indcies - at this point it looks like nothing changed
* request past 365 days to be ingested (which should use all 40 machines)
* wait
* I assign the `treeherder`alias to newly filled indexes
* drop copies

**Comment by klahnakoski** [comment]
@marco All of 2019 onward was re-ingested; 2019Q1 is finishing up now.
