### ISSUE TITLE
Ingest classification note when the classification is `intermittent`

### ISSUE THREAD

**Issue by marco-c** [klahnakoski/TestLog-ETL#75]
```
{
	"from":"treeherder",
	"select":"failure",
	"where":{"eq":{"failure.classification":"intermittent"}},
	"limit":100
}
```

Intermittent failures are classified with a bug number by sheriffs (the bug number tracking the intermittent failure). This information is missing in ActiveData.

**Comment by marco-c** [comment]
https://github.com/klahnakoski/ActiveData-ETL/blob/573a982c56b334dd1345e7e199d7e8d89c6c4728/activedata_etl/transforms/treeherder_to_normalized.py#L181-L183

Perhaps the bug ID associated to the intermittent failure is stored in yet another field?

**Comment by jmaher** [comment]
we have bug_job_map where you can do something like:
select bug_job_map.bug_id ... where job_note.failure_classification_id=4 and job_note.job_id = bug_job_map.job_id

**Comment by klahnakoski** [comment]
There is a `bugs.bug_id` property, which can have many values: 

```
{
	"from":"treeherder",
	"select":["bugs","failure","job.id"],
	"where":{"and":[
		{"gt":{"repo.push.date":{"date":"today-week"}}},
		{"in":{"repo.branch.name":["mozilla-central","mozilla-inbound","autoland"]}},
		{"ne":{"failure.classification":"not classified"}},
		{"exists":"bugs.bug_id"}
	]},
	"limit":10,
	"format":"list"
}
```

**Comment by marco-c** [comment]
Oh, thanks, I'll use that!
