### ISSUE TITLE
Link repository to Smart Scheduling project

### ISSUE THREAD

**Issue by marco-c** [klahnakoski/TestLog-ETL#79]
https://github.com/orgs/mozilla/projects/121

So we can get issues in there.

**Comment by klahnakoski** [comment]
YaS-vqpPSYCOsJUxUTl4eg and dST2VvJASmS2c4VVCsJB2A too

**Comment by klahnakoski** [comment]
done

**Comment by marco-c** [comment]
> YaS-vqpPSYCOsJUxUTl4eg and dST2VvJASmS2c4VVCsJB2A too

I imagine this comment was meant for #81 :P

**Comment by klahnakoski** [comment]
@marco-c yes, I keep mixing these two bug up.
