### ISSUE TITLE
Add percent covered to method

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#8]
It is nice to have on files, so method level is good for completeness

**Comment by chinhodado** [comment]
Done: 80253ef93d4c5de15b08b55e4445af303fa12a32

**Comment by klahnakoski** [comment]
Since you are qualifying "percentage_covered" with "method" change  `method_percentage_covered` to `method.percentage_covered`

**Comment by klahnakoski** [comment]
which it looks like you did already
