### ISSUE TITLE
`failure.notes.text` is sometimes not working

### ISSUE THREAD

**Issue by marco-c** [klahnakoski/TestLog-ETL#80]
E.g. the result for:
```
{
	"from":"treeherder",
	"select":["failure.notes.text"],
	"where":{"eq":{"run.taskcluster.id":"bHA7NFiyRialzvmjU6-K3g"}}
}
```
is:
```
"failure.notes.text":[null]
```
even though if you remove the `select` statement:
```
       "failure":{
            "auto_classification":"not classified",
            "classification":"fixed by commit",
            "notes":{
                "created":1589317937.542307,
                "failure_classification":"fixed by commit",
                "text":"86b22b1a9f7e"
            }
        },
```

The same is occurring on other tasks, e.g. TDFEix4zS96Q9QLDHVh4uw, aB9_LFOKTg2mLkuhZbxXkQ.

It doesn't apply in all cases. E.g.:
```
{
	"from":"treeherder",
	"select":["failure.notes.text"],
	"where":{"eq":{"run.taskcluster.id":"A95EfxKKTYGw0DGRiPLkSA"}}
}
```
works.

**Comment by klahnakoski** [comment]
I know the cause.  I have a potential solution.  still working on this.

**Comment by klahnakoski** [comment]
Gist of the "missing" pushes

https://gist.github.com/klahnakoski/f3e9353d1068a2485a47a24e084643e5

**Comment by klahnakoski** [comment]
@marco  I am reverting this fix.  The fix has produced a number of other problems, and this one is the smallest.
