### ISSUE TITLE
File-level markup

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#9]
Looking at 

```
# file marker
if count == 0:
    new_line.source.is_file = "true"
    new_line.source.total_covered = len(obj.covered)
    new_line.source.total_uncovered = len(obj.uncovered)
    new_line.source.percentage_covered = len(obj.covered) / (len(obj.covered) + len(obj.uncovered))
```

The file-level detail can be replicated over all coverage records, much like `run` and `build` properties are.  For example, the method level data would look like 

```
"source": {
    "file": {
        "name": obj.sourceFile,
        "covered": obj.covered,
        "uncovered": obj.uncovered,
        "total_covered": len(obj.covered),
        "total_uncovered": len(obj.uncovered),
        "percentage_covered": len(obj.covered) / (len(obj.covered) + len(obj.uncovered))
    },
    "method": {
        "name": method_name,
        "covered": method_covered,
        "uncovered": method_uncovered,
        "total_covered": len(method_covered),
        "total_uncovered": len(method_uncovered),
        "percentage_covered": len(method_covered) / (len(method_covered) + len(method_uncovered))
    }
},
```

It is important that the method-level coverage aggregates are the same as the file-level aggregates.  An extra method-level record (call it the _null_ record, with method name is set to `null`) that considers all lines (un)covered outside any method.  This null record can be the one with the `is_file` flag set.

**Comment by chinhodado** [comment]
Uhm repeating the file info in each method...and then add the file's `covered` and `uncovered` array every time...would that be a bit excessive?

I know ES will store that in an optimal way, but I'm just feeling a bit uneasy thinking about the amount of data this will generate... Would that affect ES's insertion time?

**Comment by chinhodado** [comment]
I have implemented this: 0696b62ab020c3d2dfc24b5739c0dc52e2121623 and cbb3ee7521722cf397e253b888c697e3a504033a

**Comment by klahnakoski** [comment]
The data volume and insertion time should not pose a problem.  How many method-level records are we talking about?  The cluster is currently accepting about 60million unittest records a day.

**Comment by chinhodado** [comment]
> The cluster is currently accepting about 60million unittest records a day.

Ouch. This is insignificant then :)

**Comment by klahnakoski** [comment]
Looks good!   I will add issues, if any, after a run through my debugger.
